# Generated by Django 5.1.15 on 2026-05-23 14:38

import apps.base.mixins
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga horária (h)')),
                ('periodo', models.PositiveSmallIntegerField(verbose_name='Período (1–10)')),
                ('ementa', wagtail.fields.RichTextField(verbose_name='Ementa')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
            bases=(apps.base.mixins.SeoMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='DisciplinasIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introdução')),
            ],
            options={
                'verbose_name': 'Grade de Disciplinas',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MaterialDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('slides', 'Slides'), ('pdf', 'PDF / Apostila'), ('video', 'Vídeo'), ('link', 'Link externo'), ('planilha', 'Planilha'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('url_externa', models.URLField(blank=True, verbose_name='URL externa')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_publicacao', models.DateField(verbose_name='Data de publicação')),
            ],
            options={
                'verbose_name': 'Material',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
