# Generated by Django 5.1.15 on 2026-05-23 14:38

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ensino', '0001_initial'),
        ('pessoas', '0001_initial'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinapage',
            name='docente_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='pessoas.docentepage', verbose_name='Docente responsável'),
        ),
        migrations.AddField(
            model_name='materialdisciplina',
            name='arquivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='materialdisciplina',
            name='disciplina',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='ensino.disciplinapage'),
        ),
    ]
