# Generated by Django 5.1.15 on 2026-05-23 14:38

import apps.base.mixins
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Área de Conhecimento',
                'verbose_name_plural': 'Áreas de Conhecimento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DocentesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introdução')),
            ],
            options={
                'verbose_name': 'Listagem de Docentes',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DocentePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail institucional')),
                ('lattes_url', models.URLField(blank=True, verbose_name='URL do Lattes')),
                ('orcid', models.CharField(blank=True, max_length=20, verbose_name='ORCID')),
                ('titulacao', models.CharField(choices=[('graduacao', 'Graduação'), ('especializacao', 'Especialização'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado'), ('pos_doutor', 'Pós-Doutorado')], max_length=20, verbose_name='Titulação')),
                ('instituicao_titulacao', models.CharField(max_length=200, verbose_name='Instituição de titulação')),
                ('bio', wagtail.fields.RichTextField(verbose_name='Biografia')),
                ('areas_conhecimento', modelcluster.fields.ParentalManyToManyField(blank=True, to='pessoas.areaconhecimento', verbose_name='Áreas de conhecimento')),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Perfil de Docente',
                'verbose_name_plural': 'Perfis de Docentes',
            },
            bases=(apps.base.mixins.SeoMixin, 'wagtailcore.page'),
        ),
    ]
