# Generated by Django 5.1.15 on 2026-05-23 14:38

import apps.base.mixins
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('resumo', models.TextField(max_length=200, verbose_name='Resumo')),
                ('corpo', wagtail.fields.StreamField([('paragrafo', 0), ('imagem', 3), ('documento', 6), ('embed', 7), ('citacao', 8), ('destaque', 11)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Parágrafo'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Legenda', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Arquivo'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Título do link', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('document', 4), ('title', 5)]], {}), 7: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Embed (YouTube, Vimeo…)'}), 8: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Citação'}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Informação'), ('atencao', 'Atenção'), ('importante', 'Importante')], 'label': 'Tipo'}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Texto'}), 11: ('wagtail.blocks.StructBlock', [[('tipo', 9), ('texto', 10)]], {})}, verbose_name='Conteúdo')),
                ('data_publicacao', models.DateField(auto_now_add=True, verbose_name='Data de publicação')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
            bases=(apps.base.mixins.SeoMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='PostsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Feed de Posts',
            },
            bases=('wagtailcore.page',),
        ),
    ]
