# Generated by Django 5.1.15 on 2026-05-23 14:38

import apps.base.mixins
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Documentos Institucionais',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tipo', models.CharField(choices=[('seminario', 'Seminário'), ('defesa_tcc', 'Defesa de TCC'), ('defesa_projeto', 'Defesa de Projeto'), ('workshop', 'Workshop'), ('aula_aberta', 'Aula Aberta'), ('visita_tecnica', 'Visita Técnica'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('descricao', wagtail.fields.RichTextField(verbose_name='Descrição')),
                ('data_inicio', models.DateTimeField(verbose_name='Data e hora de início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora de término')),
                ('local', models.CharField(max_length=300, verbose_name='Local')),
                ('online', models.BooleanField(default=False, verbose_name='Evento online')),
                ('link_online', models.URLField(blank=True, verbose_name='Link online')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
            bases=(apps.base.mixins.SeoMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='EventosIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Agenda de Eventos',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DocumentoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tipo', models.CharField(choices=[('regulamento', 'Regulamento'), ('formulario', 'Formulário'), ('edital', 'Edital'), ('ata', 'Ata de Reunião'), ('resolucao', 'Resolução'), ('manual', 'Manual'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_publicacao', models.DateField(verbose_name='Data de publicação')),
                ('data_vigencia', models.DateField(blank=True, null=True, verbose_name='Vigência até')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo / vigente')),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtaildocs.document', verbose_name='Arquivo (PDF)')),
            ],
            options={
                'verbose_name': 'Documento Institucional',
                'verbose_name_plural': 'Documentos Institucionais',
            },
            bases=(apps.base.mixins.SeoMixin, 'wagtailcore.page'),
        ),
    ]
