# Generated by Django 5.1.15 on 2026-05-23 14:38

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucional', '0001_initial'),
        ('pesquisa', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopage',
            name='docentes_envolvidos',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='eventos', to='pessoas.docentepage', verbose_name='Docentes envolvidos'),
        ),
        migrations.AddField(
            model_name='eventopage',
            name='projeto_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='pesquisa.projetopage', verbose_name='Projeto vinculado'),
        ),
    ]
