# Generated by Django 5.1.15 on 2026-05-23 14:38

import apps.base.mixins
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tipo', models.CharField(choices=[('pesquisa', 'Pesquisa'), ('extensao', 'Extensão'), ('ensino', 'Ensino'), ('tcc', 'TCC / Trabalho de Conclusão'), ('pibic', 'PIBIC'), ('pibex', 'PIBEX')], max_length=20, verbose_name='Tipo')),
                ('resumo', models.TextField(max_length=250, verbose_name='Resumo')),
                ('descricao', wagtail.fields.StreamField([('paragrafo', 0), ('imagem', 3), ('documento', 6), ('embed', 7), ('citacao', 8), ('destaque', 11)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Parágrafo'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Legenda', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Arquivo'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Título do link', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('document', 4), ('title', 5)]], {}), 7: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Embed (YouTube, Vimeo…)'}), 8: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Citação'}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Informação'), ('atencao', 'Atenção'), ('importante', 'Importante')], 'label': 'Tipo'}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Texto'}), 11: ('wagtail.blocks.StructBlock', [[('tipo', 9), ('texto', 10)]], {})}, verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Término')),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('suspenso', 'Suspenso'), ('submetido', 'Submetido / Aguardando aprovação')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('financiador', models.CharField(blank=True, max_length=200, verbose_name='Financiador')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
            bases=(apps.base.mixins.SeoMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ProjetosIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Listagem de Projetos',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PublicacaoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tipo', models.CharField(choices=[('artigo_periodico', 'Artigo em Periódico'), ('artigo_anais', 'Artigo em Anais de Eventos'), ('capitulo_livro', 'Capítulo de Livro'), ('livro', 'Livro'), ('relatorio_tecnico', 'Relatório Técnico'), ('tcc', 'TCC / Monografia'), ('dissertacao', 'Dissertação'), ('tese', 'Tese')], max_length=30, verbose_name='Tipo')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('corpo', wagtail.fields.StreamField([('paragrafo', 0), ('imagem', 3), ('documento', 6), ('embed', 7), ('citacao', 8), ('destaque', 11)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Parágrafo'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Legenda', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Arquivo'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Título do link', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('document', 4), ('title', 5)]], {}), 7: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Embed (YouTube, Vimeo…)'}), 8: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Citação'}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Informação'), ('atencao', 'Atenção'), ('importante', 'Importante')], 'label': 'Tipo'}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Texto'}), 11: ('wagtail.blocks.StructBlock', [[('tipo', 9), ('texto', 10)]], {})}, verbose_name='Conteúdo')),
                ('autores_externos', models.CharField(blank=True, max_length=500, verbose_name='Autores externos')),
                ('veiculo', models.CharField(max_length=300, verbose_name='Veículo de publicação')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('issn', models.CharField(blank=True, max_length=20, verbose_name='ISSN')),
                ('url_acesso', models.URLField(blank=True, verbose_name='URL de acesso')),
                ('data_publicacao', models.DateField(verbose_name='Data de publicação')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
            bases=(apps.base.mixins.SeoMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='PublicacoesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Listagem de Publicações',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProdutoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('artigo', 'Artigo'), ('relatorio', 'Relatório Técnico'), ('patente', 'Patente'), ('software', 'Software'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('data', models.DateField(verbose_name='Data')),
                ('arquivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'verbose_name': 'Produto',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
