# Generated by Django 5.1.15 on 2026-05-23 14:38

import django.db.models.deletion
import modelcluster.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pesquisa', '0001_initial'),
        ('pessoas', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetopage',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos_coordenados', to='pessoas.docentepage', verbose_name='Coordenador'),
        ),
        migrations.AddField(
            model_name='projetopage',
            name='edital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Edital'),
        ),
        migrations.AddField(
            model_name='projetopage',
            name='participantes_docentes',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='projetos_participados', to='pessoas.docentepage', verbose_name='Participantes'),
        ),
        migrations.AddField(
            model_name='projetopage',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='produtoprojeto',
            name='projeto',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='pesquisa.projetopage'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='arquivo_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='PDF'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='autores_internos',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='publicacoes', to='pessoas.docentepage', verbose_name='Autores internos'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
